label = "co_reg"
preferred_computer = "civmcluster2"

[substitutions]

[[stages]]
label = "make_header"
completion_file_pattern = "inputs/.*nhdr"
file_counter  = { type ="CountFiles", regex=".*_m[0-9]+$", multiplier=1 }
directory_pattern = "${BIGGUS_DISKUS}/co_reg_${PARAM0}-inputs"

[[stages]]
label = "ants_registration"
completion_file_pattern = "results/.*[Aa]ffine.(mat|txt)"
file_counter  = { type ="CountFiles", directory_pattern="${BIGGUS_DISKUS}/co_reg_${PARAM0}-inputs", regex=".*_m[0-9]+$", multiplier=1 }
#file_counter  = { type ="CountFiles", regex=".*_m[0-9]+$", multiplier=1 }
directory_pattern = "${BIGGUS_DISKUS}/co_reg_${PARAM0}-results"

[[stages]]
label = "apply_transform"
completion_file_pattern = "work/Reg_.*nhdr"
directory_pattern = "${BIGGUS_DISKUS}/co_reg_${PARAM0}-work"
