label = "diffusion_calc"
preferred_computer = "delos"

[substitutions]
prefix = "diffusion"
sep = ""
program = "dsi_studio"
suffix = ""

[[stages]]
label = "archive"
completion_file_pattern = "${PREFIX}${SEP}${BASE}${SEP}${PROGRAM}${SEP}${SUFFIX}"
directory_pattern = "${BIGGUS_DISKUS}/${PREFIX}${SEP}${BASE}NLSAM${SEP}${PROGRAM}${SEP}${SUFFIX}-results"
file_counter  = {type="Constant",count = 1}
preferred_computer = "delos"

[[stages]]
label = "co_reg"
completion_file_pattern = "results/co_reg.*headfile"
directory_pattern = "${BIGGUS_DISKUS}/${PREFIX}${SEP}${BASE}${SEP}${PROGRAM}${SEP}${SUFFIX}-results"

[[stages]]
label = "make_4d"
completion_file_pattern = "results/nii4D_[^_]+nii$"
directory_pattern = "${BIGGUS_DISKUS}/${PREFIX}${SEP}${BASE}${SEP}${PROGRAM}${SEP}${SUFFIX}-results"

[[stages]]
label = "dsi_studio_source"
completion_file_pattern = "work/.*src(.gz)?$"
directory_pattern = "${BIGGUS_DISKUS}/${PREFIX}${SEP}${BASE}${SEP}${PROGRAM}${SEP}${SUFFIX}-work"

[[stages]]
label = "dsi_studio_fib"
completion_file_pattern = "results/.*fib(.gz)?$"
directory_pattern = "${BIGGUS_DISKUS}/${PREFIX}${SEP}${BASE}${SEP}${PROGRAM}${SEP}${SUFFIX}-results"

[[stages]]
label = "dsi_studio_export"
completion_file_pattern = "results/.*nii.gz"
directory_pattern = "${BIGGUS_DISKUS}/${PREFIX}${SEP}${BASE}${SEP}${PROGRAM}${SEP}${SUFFIX}-results"