label = "diffusion_calc_nlsam"
preferred_computer = "civmcluster2"

[substitutions]
prefix = "diffusion"
sep = ""
program = "dsi_studio"
suffix = ""

[[stages]]
label = "co_reg"
completion_file_pattern = "results/co_reg.*headfile"
directory_pattern = "${BIGGUS_DISKUS}/${PREFIX}${SEP}${BASE}NLSAM${SEP}${PROGRAM}${SEP}${SUFFIX}-results"
file_counter  = {type="Constant",count = 1}

[[stages]]
label = "make_4d"
completion_file_pattern = "results/nii4D_${BASE}[.]nii$"
directory_pattern = "${BIGGUS_DISKUS}/${PREFIX}${SEP}${BASE}NLSAM${SEP}${PROGRAM}${SEP}${SUFFIX}-results"

[[stages]]
# create dwi average pre nlsam
# also creates a b0average, we have a testing problem in that multi-shell will create multiple dwi's
# we're ignoring that for now.
label = "make_avg"
completion_file_pattern = "results/nii4D_${BASE}_dwi.nii([.]gz)?$"
directory_pattern = "${BIGGUS_DISKUS}/${PREFIX}${SEP}${BASE}NLSAM${SEP}${PROGRAM}${SEP}${SUFFIX}-results"

#### nlsam-chunky.
[[stages]]
#label = "make_4d_nlsam"
label = "nlsam_chunky"
completion_file_pattern = "results/nii4D_[^_]+?NLSAM.nii$"
directory_pattern = "${BIGGUS_DISKUS}/${PREFIX}${SEP}${BASE}NLSAM${SEP}${PROGRAM}${SEP}${SUFFIX}-results"

[[stages]]
preferred_computer = "delos"
# create dwi average pre nlsam
# also creates a b0average, we have a testing problem in that multi-shell will create multiple dwi's
# we're ignoring that for now.
label = "make_avg"
completion_file_pattern = "results/nii4D_${BASE}NLSAM_dwi.nii([.]gz)?$"
directory_pattern = "${BIGGUS_DISKUS}/${PREFIX}${SEP}${BASE}NLSAM${SEP}${PROGRAM}${SEP}${SUFFIX}-results"

[[stages]]
preferred_computer = "delos"
label = "diffusion_nlsam_gen_fib"
completion_file_pattern = "results/.*fib(.gz)?$"
directory_pattern = "${BIGGUS_DISKUS}/${PREFIX}${SEP}${BASE}NLSAM${SEP}${PROGRAM}${SEP}${SUFFIX}-results"

[[stages]]
preferred_computer = "delos"
label = "dsi_studio_export"
# beceuase of chaos regarding the existience of nqa/qa we dont test for it, and presume we're complete if we have most things
completion_file_pattern = "results/.*${BASE}NLSAM.*[.](iso|fa|ad|rd|md)[.]nii([.]gz)?$"
directory_pattern = "${BIGGUS_DISKUS}/${PREFIX}${SEP}${BASE}NLSAM${SEP}${PROGRAM}${SEP}${SUFFIX}-results"
# count needs to match group from completion_file_pattern
file_counter  = {type="Constant",count = 5}

#[[stages]]
#label = "archive"
#completion_file_pattern = "${PREFIX}${SEP}${BASE}NLSAM${SEP}${PROGRAM}${SEP}${SUFFIX}"
#directory_pattern = "${BIGGUS_DISKUS}/${PREFIX}${SEP}${BASE}NLSAM${SEP}${PROGRAM}${SEP}${SUFFIX}-results"
#file_counter  = {type="Constant",count = 1}
#preferred_computer = "delos"
