label = "diffusion_calc_nlsam"

preferred_computer = ["civmcluster1"]

[[stages]]
label = "co_reg"
completion_file_pattern = "results/co_reg.*headfile"
directory_pattern = "${BIGGUS_DISKUS}/${PREFIX}${SEP}${BASE}NLSAM${SEP}${PROGRAM}${SEP}${SUFFIX}-results"
signature_type = "ManyToOne"

[[stages]]
label = "make_4d"
completion_file_pattern = "results/nii4D_[^_]+nii$"
directory_pattern = "${BIGGUS_DISKUS}/${PREFIX}${SEP}${BASE}NLSAM${SEP}${PROGRAM}${SEP}${SUFFIX}-results"
signature_type = "ManyToOne"

[[stages]]
label = "make_4d_nlsam"
completion_file_pattern = "results/nii4D_[^_]+?NLSAM.nii$"
directory_pattern = "${BIGGUS_DISKUS}/${PREFIX}${SEP}${BASE}NLSAM${SEP}${PROGRAM}${SEP}${SUFFIX}-results"
signature_type = "ManyToOne"

[[stages]]
label = "dsi_studio_source"
completion_file_pattern = "work/.*src(.gz)?$"
directory_pattern = "${BIGGUS_DISKUS}/${PREFIX}${SEP}${BASE}NLSAM${SEP}${PROGRAM}${SEP}${SUFFIX}-work"
signature_type = "OneToOne"
preferred_computer = ["delos"]

[[stages]]
label = "dsi_studio_fib"
completion_file_pattern = "results/.*fib(.gz)?$"
directory_pattern = "${BIGGUS_DISKUS}/${PREFIX}${SEP}${BASE}NLSAM${SEP}${PROGRAM}${SEP}${SUFFIX}-results"
signature_type = "OneToOne"
preferred_computer = ["delos"]

[[stages]]
label = "dsi_studio_export"
completion_file_pattern = "results/.*nii.gz"
directory_pattern = "${BIGGUS_DISKUS}/${PREFIX}${SEP}${BASE}NLSAM${SEP}${PROGRAM}${SEP}${SUFFIX}-results"
signature_type = "OneToMany"
required_file_keywords = [ "qa" ,"iso", "fa", "ad", "rd" ]
preferred_computer = ["delos"]
